name: Publish to PyPI

on:
  # Puedes usar 'release' si quieres publicar al crear un Release en GitHub
  # o 'push' con un filtro de tags. Elige lo que prefieras.
  release:
    types: [published]
  # O, si prefieres push de tags:
  # push:
  #   tags:
  #     - 'v*'

jobs:
  pypi-publish:
    # Nombre del job
    runs-on: ubuntu-latest
    
    # Importante: coincide con el Environment "pypi" que pusiste en PyPI
    environment: pypi

    # Permisos para OIDC
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install build
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.6.0
        with:
          publish: true
